---
- name: add Hadoop users
  user: name={{ item.name }} generate_ssh_key=yes state=present password={{ item.password }} groups={{ item.groups }}
  with_items:
    - { name: 'hdfs', groups: 'users', password: "{{ hdfs_user_pass }}" }
    - { name: 'yarn', groups: 'users', password: "{{ yarn_user_pass }}" }

- name: adding ssh keys for Hadoop users
  authorized_key: user={{ item }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  with_items:
    - hdfs
    - yarn

- name: add mapred user for JobHistoryServer
  user: name=mapred generate_ssh_key=yes state=present password={{ mapred_user_pass }} groups=users
  when: action == 'provision' and "{{ ansible_hostname }}" in "{{ groups['JobHistoryServer'] }}"

- name: adding ssh keys for mapred at JobHistoryServer
  authorized_key: user=mapred key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: action == 'provision' and "{{ ansible_hostname }}" in "{{ groups['JobHistoryServer'] }}"

- name: Install Hadoop Distribution
  synchronize: src="{{ install_directory }}/hadoop" dest="{{ install_directory }}"

- name: Setting permissions to allow hdfs, yarn and mapreduce users to write log directory
  file: path={{ install_directory}}/hadoop mode=0776
